---
#    _______________
#   |  ___________  |
#   | |           | |
#   | |   o _ o   | |
#   | |  \_____/  | |
#   | |___________| |
#   |_______________|
#    __|_________|__
#   / ************* \
#  / *************** \
#  -------------------
#
- name: Login to OpenShift cluster
  shell:
    cmd: oc login -u admin -p redhat {{ hub_cluster_host }}
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: Checking project presence
  k8s_info:
    kind: Namespace
    name: test
  register: name_test_local

- name: create project
  k8s:
    name: test
    api_version: v1
    kind: Namespace
    state: present
  when: name_test_local.resources[0].metadata.name is not defined

- name: Pause for policy to check namespace
  pause:
    seconds: 30

- name: Checking project presence
  k8s_info:
    kind: Namespace
    name: test
  register: name_test_local

- debug:
    msg: "Namespace policy should not work for stage env"
  failed_when: name_test_local.resources[0].metadata.name is not defined

- name: Remove project
  k8s:
    name: test
    api_version: v1
    kind: Namespace
    state: absent
  when: name_test_local.resources[0].metadata.name is defined
