apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
  namespace: openshift-operators
spec:
  sourceNamespace: openshift-marketplace
  source: do480-catalog
  channel: stable-3.6
  installPlanApproval: Automatic
  name: quay-operator
