apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: todonodejs
    name: frontend
  name: frontend
spec:
  host: todo.apps.shebi.northeurope.aroapp.io
  path: "/todo"
  to:
    kind: Service
    name: aro-frontend
    weight: 100
  wildcardPolicy: None
