---
- hosts: workstation
  vars_files:
    - vars/main.yaml
  module_defaults:
    group/k8s:
      ca_cert: "/etc/pki/tls/certs/ca-bundle.crt"
      kubeconfig: "{{ kubeconfig }}"
  roles:
    - remove_roles
