---
#    _______________
#   |  ___________  |
#   | |           | |
#   | |   o _ o   | |
#   | |  \_____/  | |
#   | |___________| |
#   |_______________|
#    __|_________|__
#   / ************* \
#  / *************** \
#  -------------------
#
- name: Login to OpenShift cluster
  shell:
    cmd: oc login -u admin -p redhat {{ hub_cluster_host }}
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: Check RHACM cluster labels
  k8s_info:
    api_version: cluster.open-cluster-management.io/v1
    kind: ManagedCluster
    name: local-cluster
  register: local_cluster_label

- name: check local-cluster label
  debug:
    msg: "`env=stage` label is missing."
  failed_when: local_cluster_label.resources[0].metadata.labels.env != "stage"

- name: Check RHACM cluster labels
  k8s_info:
    api_version: cluster.open-cluster-management.io/v1
    kind: ManagedCluster
    name: managed-cluster
  register: managed_cluster_label

- name: check managed-cluster label
  debug:
    msg: "`env=prod` label is missing."
  failed_when: managed_cluster_label.resources[0].metadata.labels.env != "prod"