---
- name: Deploy HTPasswd identityProviders
  hosts: localhost
  become: true

  tasks:

  - name: Create localaccess HTPasswd identityProviders in OpenShift
    community.okd.k8s:
      state: present
      definition: "{{ lookup('template', 'templates/htpasswd_identity.yaml.j2') }}"

  - name: Create cluster-admin User in localaccess HTPasswd identityProviders with cluster-admin role
    community.okd.k8s:
      state: present
      definition: "{{ lookup('template', 'templates/htpasswd_user.yaml.j2') }}"


  - name: Save password in a local file
    ansible.builtin.copy:
      content: "{{ content }}"
      dest: "{{ dest }}"
      mode: 384

  - name: Apply HTPasswd identityProviders in identityproviders.config.openshift.io using HTPasswd item.username and item.password
    community.okd.openshift_auth:
        host: "{{ host }"
      register: k8s_}auth_results
  
