apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: argocd-urp
  namespace: si-policies
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/controls: ""
    policy.open-cluster-management.io/standards: ""
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: awf-admin-sa
        spec:
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
            include:
              - "*"
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: awf-admin-sa
                rules:
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - eventsources
                      - sensors
                      - workflows
                      - workfloweventbindings
                      - workflowtemplates
                      - cronworkflows
                    verbs:
                      - get
                      - list
                      - watch
                      - delete
                      - patch
                      - update
                  - apiGroups:
                      - "*"
                    resources:
                      - events
                    verbs:
                      - create
                      - watch
                      - patch
                  - apiGroups:
                      - "*"
                    resources:
                      - serviceaccounts
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - "*"
                    resources:
                      - secrets
                    verbs:
                      - create
                      - get
                  - apiGroups:
                      - apigroups
                    resources:
                      - secrets
                    verbs:
                      - get
                      - update
                  - apiGroups:
                      - "*"
                    resources:
                      - pods
                      - pods/log
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - watch
                      - delete
                  - apiGroups:
                      - "*"
                    resources:
                      - configmaps
                      - events
                    verbs:
                      - get
                      - list
                      - watch
          pruneObjectBehavior: DeleteAll
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: awf-default-sa
        spec:
          namespaceSelector:
            exclude: []
            include:
              - argo
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: awf-default-sa
                rules:
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - eventsources
                      - sensors
                      - workflows
                      - workfloweventbindings
                      - workflowtemplates
                      - cronworkflows
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - "*"
                    resources:
                      - events
                    verbs:
                      - watch
                  - apiGroups:
                      - "*"
                    resources:
                      - pods
                      - pods/log
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - "*"
                    resources:
                      - configmaps
                      - events
                    verbs:
                      - get
                      - list
                      - watch
          pruneObjectBehavior: DeleteAll
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: eventsource-urp
        spec:
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
            include:
              - "*"
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: eventsource-urp
                rules:
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - namespaces
                    verbs:
                      - get
                      - list
                      - patch
          pruneObjectBehavior: DeleteAll
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: userresources-cluster
        spec:
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
            include:
              - "*"
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: userresources-cluster
                rules:
                  - apiGroups:
                      - "*"
                    resources:
                      - namespaces
                    verbs:
                      - get
                      - list
                      - patch
          pruneObjectBehavior: DeleteAll
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: userresources-argo
        spec:
          namespaceSelector:
            exclude: []
            include:
              - argo
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: userresources-argo
                rules:
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - applications
                      - appprojects
                    verbs:
                      - create
                      - get
                      - list
                      - watch
                      - update
                      - patch
                      - delete
                  - apiGroups:
                      - "*"
                    resources:
                      - pods
                    verbs:
                      - get
                      - patch
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - workflowtaskresults
                    verbs:
                      - create
                      - patch
          pruneObjectBehavior: DeleteAll
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: argo-namespace
        spec:
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
            include:
              - "*"
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: argo
          pruneObjectBehavior: None
          remediationAction: enforce
          severity: low
status:
  compliant: Compliant
  placement:
    - placement: argocd-urp-placement
      placementBinding: argocd-urp-placement
