apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: urp-permissions
  namespace: si-policies
  annotations:
    policy.open-cluster-management.io/categories: AC Access Control, CM Configuration Management
    policy.open-cluster-management.io/controls: AC-3 Access Enforcement, CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
  creationTimestamp: 2023-07-19T09:24:23Z
  generation: 8
  managedFields:
  resourceVersion: "10923368"
  uid: 62997118-1c41-4c34-bb09-007f9d082326
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: argocd-application-controller
        spec:
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
            include:
              - "*"
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: argocd-application-controller
                rules:
                  - apiGroups:
                      - "*"
                    resources:
                      - "*"
                    verbs:
                      - "*"
          pruneObjectBehavior: DeleteAll
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: argocd-dex-server
        spec:
          namespaceSelector:
            exclude: []
            include:
              - openshift-gitops
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: argocd-dex-server
                rules:
                  - apiGroups:
                      - "*"
                    resources:
                      - secrets
                      - configmaps
                    verbs:
                      - get
                      - list
                      - watch
          pruneObjectBehavior: DeleteAll
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: redis
        spec:
          namespaceSelector:
            exclude: []
            include:
              - openshift-gitops
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: redis
                rules:
                  - apiGroups:
                      - "*"
                    resources:
                      - "*"
                    verbs:
                      - get
                      - list
                      - watch
                      - delete
                      - patch
          pruneObjectBehavior: DeleteAll
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: argocd-server
        spec:
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
            include:
              - "*"
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: argocd-server
                rules:
                  - apiGroups:
                      - "*"
                    resources:
                      - "*"
                    verbs:
                      - get
                      - delete
                      - patch
                  - apiGroups:
                      - "*"
                    resources:
                      - events
                    verbs:
                      - list
                  - apiGroups:
                      - "*"
                    resources:
                      - pods
                      - pods/log
                    verbs:
                      - get
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - applications
                    verbs:
                      - get
                      - list
                      - update
                      - watch
          pruneObjectBehavior: DeleteAll
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: argocd-repo-server
        spec:
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
            include:
              - "*"
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: argocd-repo-server
                rules:
                  - apiGroups:
                      - "*"
                    resources:
                      - "*"
                    verbs:
                      - "*"
          pruneObjectBehavior: DeleteAll
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: argocd-applicationset-controller
        spec:
          namespaceSelector:
            exclude: []
            include:
              - openshift-gitops
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: argocd-applicationset-controller
                rules:
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - applications
                      - applicationssets
                      - applicationsets/finalizers
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - watch
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - appprojects
                    verbs:
                      - get
                  - apiGroups:
                      - "*"
                    resources:
                      - configmaps
                    verbs:
                      - create
                      - update
                      - delete
                      - get
                      - list
                      - patch
                      - watch
                  - apiGroups:
                      - "*"
                    resources:
                      - secrets
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - apps
                      - extensions
                    resources:
                      - deployments
                    verbs:
                      - get
                      - list
                      - watch
          pruneObjectBehavior: DeleteAll
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: argocd-notifications-controller
        spec:
          namespaceSelector:
            exclude: []
            include:
              - openshift-gitops
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: argocd-notifications-controller
                rules:
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - applications
                      - appprojects
                    verbs:
                      - get
                      - list
                      - watch
                      - update
                      - patch
                  - apiGroups:
                      - "*"
                    resources:
                      - confirmaps
                      - secrets
                    verbs:
                      - list
                      - watch
                  - apiGroups:
                      - "*"
                    resources:
                      - configmaps
                    verbs:
                      - get
                  - apiGroups:
                      - "*"
                    resources:
                      - secrets
                    verbs:
                      - get
          pruneObjectBehavior: DeleteAll
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-gitops-ns
        spec:
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-gitops
          pruneObjectBehavior: None
          remediationAction: enforce
          severity: low
status:
  compliant: Compliant
  placement:
    - placement: urp-permissions-placement
      placementBinding: urp-permissions-placement
  status:
    - clustername: local-cluster
      clusternamespace: local-cluster
      compliant: Compliant
    - clustername: single-node-2
      clusternamespace: single-node-2
      compliant: Compliant
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: urp-permissions-placement
  namespace: si-policies
  creationTimestamp: 2023-07-19T09:24:23Z
  generation: 1
  resourceVersion: "10896217"
  uid: 1ee38afb-3160-410c-86c3-6df443fb6bde
spec:
  clusterSets:
    - si-cluster
status:
  conditions:
    - lastTransitionTime: 2023-07-19T09:24:23Z
      message: Placement configurations check pass
      reason: Succeedconfigured
      status: "False"
      type: PlacementMisconfigured
    - lastTransitionTime: 2023-07-19T09:24:23Z
      message: All cluster decisions scheduled
      reason: AllDecisionsScheduled
      status: "True"
      type: PlacementSatisfied
  numberOfSelectedClusters: 2
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: urp-permissions-placement
  namespace: si-policies
  creationTimestamp: 2023-07-19T09:24:23Z
  generation: 1
  resourceVersion: "10896210"
  uid: 83da2132-8cd2-4295-a0c0-da6ee9cc1f68
placementRef:
  name: urp-permissions-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: urp-permissions
    apiGroup: policy.open-cluster-management.io
    kind: Policy

