---
- hosts: workstation
  vars_files:
    - vars/main.yaml
  module_defaults:
    group/k8s:
      host: "{{ hub_cluster_host }}"
      kubeconfig: "/home/lab/ocp4/auth/kubeconfig"
  roles:
    - ocp_sync_ldap_groups
