---
- hosts: workstation
  vars_files:
    - vars/main.yaml
  module_defaults:
    group/k8s:
      ca_cert: "/etc/pki/tls/certs/ca-bundle.crt"
      host: "{{ hub_cluster_host }}"
      kubeconfig: "{{ kubeconfig }}"
    ipa_user:
      ipa_host: "{{ ipa_host }}"
      ipa_user: "{{ ipa_user }}"
      ipa_pass: "{{ ipa_pass }}"
      validate_certs: no
  roles:
    - quay_install
