---
#    _______________
#   |  ___________  |
#   | |           | |
#   | |   o _ o   | |
#   | |  \_____/  | |
#   | |___________| |
#   |_______________|
#    __|_________|__
#   / ************* \
#  / *************** \
#  -------------------
#


- name: Open port 514
  firewalld:
    port: 514/tcp
    permanent: yes
    state: enabled

- name: Reload firewalld service
  systemd:
    name: firewalld
    state: reloaded

- name: Enable imtcp module
  replace:
    path: /etc/rsyslog.conf
    regexp: '^#(.*="imtcp.*)'
    replace: '\1'

- name: Adding RemoteLogs template
  blockinfile:
    dest: /etc/rsyslog.conf
    marker: "## {mark} Adding RemoteLogs template"
    block: |
      $template RemoteLogs, "/var/log/remote/%HOSTNAME%.log"
      local0.* ?RemoteLogs
    state: present

- name: Restart rsyslog service service
  service:
    name: rsyslog
    state: restarted
    enabled: true
