additionalTrustBundlePolicy: Proxyonly
apiVersion: v1
baseDomain: k8sop-dev.system-a.local
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: cl-008
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    apiVIPs:
    - 172.19.213.13
    failureDomains:
    - name: generated-failure-domain
      region: generated-region
      server: app444006.system.local
      topology:
        computeCluster: /Datacenter-Produktion/host/VM_CL_K8SOP
        datacenter: Datacenter-Produktion
        datastore: /Datacenter-Produktion/datastore/VM_Produktion/DSCL_VM-SVC-K8SOP_AtlasEdge/VM-SVC-K8SOP_01
        networks:
        - 613_PF-OSH2-EA
        resourcePool: /Datacenter-Produktion/host/VM_CL_K8SOP/Resources/RP_NOP
        folder: /Datacenter-Produktion/vm/Servergruppen/APP615XXX/develop
      zone: generated-zone
    ingressVIPs:
    - 172.19.213.12
    vcenters:
    - datacenters:
      - Datacenter-Produktion
      password: 9F2SHqeR*7aVmgU
      port: 443
      server: app444006.system.local
      user: system\ZA-SVC-OCP-VM
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMWViNTFiYjY4ZjI3NDkzZGJiMTM5YTRkM2M3MGM0YWQ6RlhJSktTUjBUWlBJTzNVRDMzOFEwTDJTRVFHSlc4NkZJWkZESElLUjVLRUZaWjNTMEpaMDVIWk5YS0RDUjFPNw==","email":"serodrig@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMWViNTFiYjY4ZjI3NDkzZGJiMTM5YTRkM2M3MGM0YWQ6RlhJSktTUjBUWlBJTzNVRDMzOFEwTDJTRVFHSlc4NkZJWkZESElLUjVLRUZaWjNTMEpaMDVIWk5YS0RDUjFPNw==","email":"serodrig@redhat.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTFiMmVjY2VlLWIyNzctNGJhMy05OThmLWJlZWRjYmFlMTYzZTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTNOREEyWVdSa01UVXpaRGMwTkRWbE9ETmtOV1ZqTlRWa01qTTBORE0zTmlKOS5ZejIxc1VCVlVkNlI2S0d5Ni1LdUJKSEE3d00tSC11NGpERm1TSkd2ZWZST21nSUc5b1doeUlCOE5HVk1BZ0dVUmtrNmh6a2JNcy1vdU9tVjFDT0taY2tvdl92S3dJLS1na0pMWWxtbWxYS1k5YlhYSVp6SzI5RFJ3c3FFMjZIVEtaTWJKVjJ4VjN3X0hGZGZaaG55MWRXUGxQdUQ4MThKYVJzN0NPaDJfNTZSTk1IS1hPQ2M3YVhlQzhtblpvdVFTV0FmRzRNanJkdTJmMElENU41XzRkTUtscEFTSUREcnhSak5jY0lDdjE2UFZvVy05OHFoOFpKREFTWGI0MzVNeS1jNnpDTWlfTWpvWGo5UlQwckotZlJjbzZBYjlNU19ESXU1WURUVDZHOHE4LTJYZG5USXFrb0hKWWpDZmJsZkdVNnVBSzdrcDNPQXJ0MlRzZjNJX2VPQ1gyQ1NwaEdLRmpXSUFtSFYzSHB6QU16Wk1DUFpKNTZFb0pIbDNyUThUQjQwcHhFT0dfLWNMWEpxWkZQNTJ5cnEtSm5yNEJJUDVHVXNrQnVaSGZoTVMzX050OXlvMFVrd0NFS3NnYmNDN1JDd0NLNmxJaERGaU5aa1RWU2I0VXJmY0ZjbWJPcGRrOUYzUG5zY1k5dUlsZ0lONTFiMHl6MmVYUnl1WFREQ19UWnNSZC1tbkxBZ2ZRWU9nbFE4RFJ3WWpBQVFNcUlsTkowb1piR0ROcjdPbzhwZlBWeTF0Zk9qMS1mSGF6dk9CbzF0NzFIdklqZXRKRVBHZjRadk9FREdwNm02emdmaW5FdEZESHphTkVvYURlQnltd2JWemJOc1g3VjA5WndwWGktNnRpNURhUDhEeUoxcUtTMER1Ymd0a0hVcDNmdGZxUE1NMVlxWVliYw==","email":"serodrig@redhat.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTFiMmVjY2VlLWIyNzctNGJhMy05OThmLWJlZWRjYmFlMTYzZTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTNOREEyWVdSa01UVXpaRGMwTkRWbE9ETmtOV1ZqTlRWa01qTTBORE0zTmlKOS5ZejIxc1VCVlVkNlI2S0d5Ni1LdUJKSEE3d00tSC11NGpERm1TSkd2ZWZST21nSUc5b1doeUlCOE5HVk1BZ0dVUmtrNmh6a2JNcy1vdU9tVjFDT0taY2tvdl92S3dJLS1na0pMWWxtbWxYS1k5YlhYSVp6SzI5RFJ3c3FFMjZIVEtaTWJKVjJ4VjN3X0hGZGZaaG55MWRXUGxQdUQ4MThKYVJzN0NPaDJfNTZSTk1IS1hPQ2M3YVhlQzhtblpvdVFTV0FmRzRNanJkdTJmMElENU41XzRkTUtscEFTSUREcnhSak5jY0lDdjE2UFZvVy05OHFoOFpKREFTWGI0MzVNeS1jNnpDTWlfTWpvWGo5UlQwckotZlJjbzZBYjlNU19ESXU1WURUVDZHOHE4LTJYZG5USXFrb0hKWWpDZmJsZkdVNnVBSzdrcDNPQXJ0MlRzZjNJX2VPQ1gyQ1NwaEdLRmpXSUFtSFYzSHB6QU16Wk1DUFpKNTZFb0pIbDNyUThUQjQwcHhFT0dfLWNMWEpxWkZQNTJ5cnEtSm5yNEJJUDVHVXNrQnVaSGZoTVMzX050OXlvMFVrd0NFS3NnYmNDN1JDd0NLNmxJaERGaU5aa1RWU2I0VXJmY0ZjbWJPcGRrOUYzUG5zY1k5dUlsZ0lONTFiMHl6MmVYUnl1WFREQ19UWnNSZC1tbkxBZ2ZRWU9nbFE4RFJ3WWpBQVFNcUlsTkowb1piR0ROcjdPbzhwZlBWeTF0Zk9qMS1mSGF6dk9CbzF0NzFIdklqZXRKRVBHZjRadk9FREdwNm02emdmaW5FdEZESHphTkVvYURlQnltd2JWemJOc1g3VjA5WndwWGktNnRpNURhUDhEeUoxcUtTMER1Ymd0a0hVcDNmdGZxUE1NMVlxWVliYw==","email":"serodrig@redhat.com"}}}'
